# Generated by Django 6.0.7 on 2026-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность"),
        ),
    ]
