# Generated by Django 6.0.7 on 2026-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="lesson",
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=1000,
                null=True,
                verbose_name="Ссылка оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите Id сессии", max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
