# Generated by Django 6.0.7 on 2026-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payments_lesson_payments_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("pending", "Ожидает оплаты"), ("paid", "Оплачено")],
                default="pending",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
