# Generated by Django 6.0.7 on 2026-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Ожидает оплаты"), ("paid", "Оплачено")],
                default="pending",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
