# Generated by Django 6.0.7 on 2026-08-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_payments_payment_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="payment_status",
            new_name="payment_method",
        ),
    ]
