# Generated by Django 6.0.8 on 2026-08-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_payment_status_payments_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_update_materials",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату последнего обновления материала",
                null=True,
                verbose_name="Последнее обновление материала",
            ),
        ),
    ]
