# Generated by Django 6.0.8 on 2026-08-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_subscription_last_update_materials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="last_update_materials",
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_seen_update_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату последнего обновления материала",
                null=True,
                verbose_name="Последнее обновление материала",
            ),
        ),
    ]
