# Generated by Django 6.0.7 on 2026-07-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выбери курс урока",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
