# Generated by Django 6.0.7 on 2026-07-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
