# Generated by Django 6.0.7 on 2026-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Укажите стоимость курса", null=True, verbose_name="Стоимость"
            ),
        ),
    ]
