# Generated by Django 6.0.8 on 2026-08-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_material_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату загрузки обновления курса",
                null=True,
                verbose_name="Дата загрузки обновления",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Укажите дату обновления курса", null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_material_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату загрузки обновления урока",
                null=True,
                verbose_name="Дата загрузки обновления",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Укажите дату обновления урока", null=True, verbose_name="Дата обновления"
            ),
        ),
    ]
