# Generated by Django 6.0.8 on 2026-08-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_course_last_material_update_course_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="last_material_update",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="last_material_update",
        ),
    ]
